enyo.depends(
  'Clipping.js',
  'Document.js',
  'DocumentCollection.js',
  'DocumentSelectorList.js',
  'DocumentSelectorItem.js',
  'DocumentView.js',
  'DocumentControl.js',
  'CopyToClipboardIconButton.js'
);
