enyo.depends(
  'DefaultSettings.js',
  'SettingsSingleton.js',
  'SettingsSlideable.js',
  'SettingsPanel.js',
  'SettingsItem.js',
  'SettingsActionItem.js',
  'SettingsValueItem.js',
  'SettingsTextInput.js',
  'SettingsRadioGroup.js',
  'SettingsThemeRadioGroup.js',
  'SettingsFontRadioGroup.js',
  'SettingsFontSizeSlider.js',
  'SettingsTextMarginSlider.js',
  'RevokeEvernotePermissionsActionItem.js'
);
